### ISSUE TITLE
Get HP Warranty from CMDB??

### ISSUE THREAD

**Issue by bclaps** [dotps1/HPWarranty#13]
It looks like that function is missing. Can you add that back in? That was my life saver.

**Comment by dotps1** [comment]
really!  lol, I didn't think anyone used it ;)  ill get it back in today or tomorrow at the latest.

thanks.

**Comment by bclaps** [comment]
Thank you for putting it back in! Is there an easy way to write out the computer name and the fields from the script to a CSV file?

**Comment by bclaps** [comment]
It's saying Get-HPComputerInformationForWarrantyFromCMDB is not a recognize as the name of a cmdlet

**Comment by dotps1** [comment]
Strange, it is working for me, here is a the screen shot:

![image](https://cloud.githubusercontent.com/assets/1016996/10221270/5b8d86bc-681b-11e5-8db8-9e460b7aba50.png)

I'm not sure why it would not be working for you.

**Comment by bclaps** [comment]
same file uploaded that you have?

**Comment by dotps1** [comment]
I think so, I did just check in some added changes, error handling and such.  the latest is 2.1.0.2, your welcome to give it another try.

thanks.

**Comment by bclaps** [comment]
My apologies, i wasn't forcing the install of the new versions... all is well in the world again. Thank you :)

**Comment by dotps1** [comment]
lol, no problem, I got the help file working now too, so that is a bonus as well.  It is also now updated on the PSGallery as well:  https://www.powershellgallery.com/packages/HPWarranty/2.1.0.2

thanks for your feed back, and let me know if you find anything else.

**Comment by dotps1** [comment]
@bclaps  you may want to get the latest version, I found bug today in this function: https://github.com/dotps1/HPWarranty/issues/14
just an FYI
