### ISSUE TITLE
Write-Error : Cannot convert 'System.Object[]' to the type 'System.String' 

### ISSUE THREAD

**Issue by MartinHen** [dotps1/HPWarranty#19]
Let me start off by saying that this script is a life-saver.. If I can get it to work.
And making it, makes you a star.

However, I have been running into a issue with the script. 
I am attempting to use it in order to lookup a warranty by providing the SN SKU and ComputerName as a parameter for the script. Instead of having the script collect these. 
And it works perfectly.

My problem however seem to be when I reach the following part in Get-HPIncWarrantyEntitlement.ps1 ;
Write-Error -Message $($entitlement.GetElementsByTagName('DataPayLoad').InnerText) -ErrorId $($entitlement.GetElementsByTagName('ErrorID').InnerText)

This line throws me the following error ;

Write-Error : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified m
ethod is not supported.
At C:\bleh\HP\HPWarranty\Functions\Get-HPIncWarrantyEntitlement.ps1:93 char:42
+ ... or -Message $($entitlement.GetElementsByTagName('DataPayLoad').InnerT ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Error], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.WriteErrorCommand

Any ideas and/or tips?

**Comment by MartinHen** [comment]
I changed the Write-Error line to simply return $entitlement in order to see the syntax it is handeling and got the following result:

xml                            EIAMessage
---                            ----------
version="1.0" encoding="UTF-8" EIAMessage

To me that looks like there might be a issue somewhere else?

**Comment by dotps1** [comment]
basically it only throws the error if $entitlement -eq $null:

```PowerShell
            if ($entitlement -ne $null) {
                if ($entitlement.GetElementsByTagName('ErrorID').InnerText -ne $null) {
                    Write-Error -Message $($entitlement.GetElementsByTagName('DataPayLoad').InnerText) -ErrorId $($entitlement.GetElementsByTagName('ErrorID').InnerText)
                    continue
``` 

so the request is returning nothing.  but this is working for you on other PC's?  would you be willing to supply me with the SN and SKU for troubleshooting?

**Comment by MartinHen** [comment]
It is not working on any PC at the moment.
Absolutely, at this point I am willing to do anything for a working solution. I will most likely be thinking of this the entire weekend.

SN ; CZC3151FJ3
SKU ; A2K86ET#UUW
(Sweden)
I should mention that I changed the Country code section of the script from 'US' to 'SE'.

**Comment by dotps1** [comment]
This works fine for me with the following code:

```PowerShell
Get-HPIncWarrantyEntitlement -ProductNumber 'A2K86ET#UUW' -SerialNumber 'CZC3151FJ3' -CountryCode SE
```

![image](https://cloud.githubusercontent.com/assets/1016996/11444972/69c4e416-94f6-11e5-98d9-39b274854771.png)


maybe there is an issue blocking on your network.

**Comment by dotps1** [comment]
this did expose another bug!  thanks!  https://github.com/dotps1/HPWarranty/issues/20
