### ISSUE TITLE
Get-HPWarrantyEntitlement - Issue with HPE Networking Warranty Check

### ISSUE THREAD

**Issue by kentucker5** [dotps1/HPWarranty#22]
Hello there,

I would like to raise a new issue when checking HPE Networking Serial numbers for warranty. 

I am getting the following output:
My CSV has "SerialNumber,ProductNumber" columns. 

PS U:\> Import-Csv u:\import.csv | Get-HPWarrantyEntitlement | Export-Csv u:\export.csv
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:87 char:5
+     $responseStream = ($soapWebRequest.GetResponse()).GetResponseStre ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:90 char:5
+     $returnXml = [Xml]$soapReader.ReadToEnd()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:92 char:5
+     $responseStream.Close()
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Get-HPWarrantyEntitlement : No entitlement found.
At line:1 char:28
+ Import-Csv u:\import.csv | Get-HPWarrantyEntitlement | Export-Csv u:\ ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-HPWarrantyEntitlement

Thanks
Ken

**Comment by dotps1** [comment]
Sorry, i had already opened an issue for this https://github.com/dops1/HPWarranty/issues/21 and i also cleanded up the error output so it doesn't return 5 errors only 1.  My guess is that they have done away with the ISEE and have gone to a more standard web service as they did with the workstations.

im going to close this issue, please reference issue 21.  thanks.
