### ISSUE TITLE
Cache registration tokens for HP Enterprise requests

### ISSUE THREAD

**Issue by beanska** [dotps1/HPWarranty#27]
Currently every call to `Get-HPEntWarrantyEntitlement` performs a new registration to get the registration token. It should be possible to write the registration to a text file and use it until expiration. Reasoning would be to lessen the calls to ISEE and not lead to HP preventing us from querying the service.

**Comment by dotps1** [comment]
if you pipe your values into the cmdlet, it should only do it once.  But, i do like the idea, we could create an $env variable as well to hold the data. and destroy null it when the module is re loaded.  Let me think about it for a little bit.

**Comment by beanska** [comment]
Personally I never use the -ComputerName because I am feeding values from
SQL server.

I looked at implementing this but it is tricky without changing a huge
amount of code. I started ripping out the "Begin, Process, End" bits and it
quickly became a total refactor and I abandoned it.

I notice in Process{} you are not using the $_ object and you treat
$ComputerObject as a String array. If you are piping objects in you should
not need the ComputerName parameter as Process{} is going to loop over each
$_ object for you.


On Thu, Jun 16, 2016 at 11:06 AM, Thomas Malkewitz <notifications@github.com

**Comment by dotps1** [comment]
Right, that allows you to do either computer1, computer2 | Get-HPIncWarrantyEntitlement
Or
Get-HPIncWarrantyEntitlement -ComputerName computer1, computer2

But, I do like the idea of caching that token, just have to think about how I want to do it.  And because it never needs to be accessed by the user, a script scoped one should work.  I will play with it after lunch.

**Comment by dotps1** [comment]
ok, @beanska i think i got it working, please give it a try.  Basically it will use a Script scoped variable `HPEntRegistration`, it is a HashTable
```PowerShell
$Script:HPEntRegistration = @{
    Gdid = '<Gdid>'
    Token = '<Token>'
    DateTime = Get-Date
}
```

So, when you first import the module (or re import using -Force) it will create this empty hashtable, once the first request is made, it will populate those three Key/Values.  Upon the next request, if the current date time is greater then 15 minutes from the `DateTime` Value, it will create a new registration request, and then update the HashTable Values.  I am pretty sure if the Gdid and Token values are only valid for a given amount of time.  If 15 minutes is working well, we can increase it.  I only have a about 3 server SN/PN to work with, so please test this out at let me know what you think!  Thanks for your help.

**Comment by beanska** [comment]
Thanks, it works, I was thinking more long term by writing it to a file but this is good.

**Comment by dotps1** [comment]
yeah, im pretty sure those values are time sensitive, but it may have been up to an hour, so we can increase that value once and see what happens.
