### ISSUE TITLE
Not Detecting the Manufacturer name currently

### ISSUE THREAD

**Issue by draco6576** [dotps1/HPWarranty#29]
I get the following when I try to run the command against one of my servers...

Get-HPIncWarrantyEntitlement -ComputerName <servername> -Credential <Cred>
Get-HPProductNumberAndSerialNumber : Computer Manufacturer is not of type Hewlett-Packard.  This cmdlet can only be used with values from Hewlett-Packard systems.
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.5.9\Public\Get-HPIncWarrantyEntitlement.ps1:73 char:53

The thing is that this is an HP server...

Get-WmiObject win32_computersystem -ComputerName <servername> | Select-Object Manufacturer,Model

Manufacturer Model               
------------ -----               
HP           ProLiant DL380p Gen8

**Comment by dotps1** [comment]
I just pushed a fix, but only to the repo, not to the PSGallery.  Can you download the source from [here](https://github.com/dotps1/HPWarranty/tree/master/HPWarranty) and see if it works for you now,  I think it was this line of code in the private Get-HPProductNumberAndSerialNumber cmdlet
```PowerShell
$manufacturer = Get-CimInstance -CimSession $cimSession -ClassName Win32_ComputerSystem -ErrorAction Stop

if ($manufacturer -eq 'Hewlett-Packard' -or $manufacturer -eq 'HP') { ...
```
Based on that, I never selected the Manufacturer portion of code.  I'm honestly surprised that it made it this far without someone catching that.  Anyway here is the updated code:

```PowerShell
        $manufacturer = Get-CimInstance -CimSession $cimSession -ClassName Win32_ComputerSystem -ErrorAction Stop | 
            Select-Object -ExpandProperty Manufacturer

        if ($manufacturer -eq 'Hewlett-Packard' -or $manufacturer -eq 'HP') { ...
```

So it _should_ work now.  I don't have any HPs on site here to test with, so please let me know if it works so I can push this fix to the PSGallery.

Thanks.

**Comment by jbruettcva** [comment]
Assuming that the code fix effects the HPEnt cmdlet the same as the HPInc cmdlet, this is working as expected.

```powershell
Get-HPEntWarrantyEntitlement -ComputerName XXXXXXXXX -Credential cov\jbadmin

Name                           Value
----                           -----
SerialNumber                   XXXXXXXXX
ActiveEntitlement              true
OverallEntitlementStartDate    2016-04-25
ProductNumber                  800079-S01
ComputerName                   XXXXXXXXX
OverallEntitlementEndDate      2019-05-24
```

**Comment by dotps1** [comment]
yeah, its the same call for each cmdlet, thanks!

**Comment by dotps1** [comment]
hey, no worries @draco6576, its not published to the PSGallery so you can grab it from there if you'd like!  https://www.powershellgallery.com/packages/HPWarranty/2.6.0

thanks for reporting, I'm still surprised it made it this far without being caught lol, guess no one is really calling out to the computer directly to get the serial/product number.
