### ISSUE TITLE
Unable to connect to SCCM 2012 R2 SQL

### ISSUE THREAD

**Issue by computerman9999** [dotps1/HPWarranty#3]
When reviewing and trying the code to pull from MS SCCM 2012 R2 U2, none of the tables exist.

**Comment by dotps1** [comment]
I do not have access to an SCCM 2012 R2 DB to test sorry.

**Comment by computerman9999** [comment]
I have updated the SQL myself.  I will post when I have it working.

**Comment by dotps1** [comment]
Closing, no response.
