### ISSUE TITLE
enhancement: Save XML Response to Folder 

### ISSUE THREAD

**Issue by RonnyBunke** [dotps1/HPWarranty#6]
To the individual case to see the response from HP.
I've added this option and would be glad if this is included in the code with.

        [Parameter()]
        [ValidateScript({ if (Test-Path -Path $_) { $true } })]
        [String]
        $XMLOutputSaveDir

    if ($XMLOutputSaveDir) {
       if ($XMLOutputSaveDir -notlike "*\") {$XMLOutputSaveDir += "\"}
    ([Xml]$entitlementAction.Envelope.Body.GetOOSEntitlementList2Response.GetOOSEntitlementList2Result.Response).save($XMLOutputSaveDir + $SerialNumber + ".xml" )
    }

**Comment by dotps1** [comment]
I love it!  Great idea, ill try to take care of it today b

Sent from my Windows Phone
________________________________

**Comment by dotps1** [comment]
I have implemented the change, it seems to be working well.  thanks again.
